/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TimeTrackingImport } from './routes/time-tracking'
import { Route as RecruitmentImport } from './routes/recruitment'
import { Route as PayrollManagementImport } from './routes/payroll-management'
import { Route as EmployeeManagementImport } from './routes/employee-management'
import { Route as DocumentManagementImport } from './routes/document-management'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AttendanceManagementImport } from './routes/attendance-management'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TimeTrackingRoute = TimeTrackingImport.update({
  path: '/time-tracking',
  getParentRoute: () => rootRoute,
} as any)

const RecruitmentRoute = RecruitmentImport.update({
  path: '/recruitment',
  getParentRoute: () => rootRoute,
} as any)

const PayrollManagementRoute = PayrollManagementImport.update({
  path: '/payroll-management',
  getParentRoute: () => rootRoute,
} as any)

const EmployeeManagementRoute = EmployeeManagementImport.update({
  path: '/employee-management',
  getParentRoute: () => rootRoute,
} as any)

const DocumentManagementRoute = DocumentManagementImport.update({
  path: '/document-management',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AttendanceManagementRoute = AttendanceManagementImport.update({
  path: '/attendance-management',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/attendance-management': {
      id: '/attendance-management'
      path: '/attendance-management'
      fullPath: '/attendance-management'
      preLoaderRoute: typeof AttendanceManagementImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/document-management': {
      id: '/document-management'
      path: '/document-management'
      fullPath: '/document-management'
      preLoaderRoute: typeof DocumentManagementImport
      parentRoute: typeof rootRoute
    }
    '/employee-management': {
      id: '/employee-management'
      path: '/employee-management'
      fullPath: '/employee-management'
      preLoaderRoute: typeof EmployeeManagementImport
      parentRoute: typeof rootRoute
    }
    '/payroll-management': {
      id: '/payroll-management'
      path: '/payroll-management'
      fullPath: '/payroll-management'
      preLoaderRoute: typeof PayrollManagementImport
      parentRoute: typeof rootRoute
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentImport
      parentRoute: typeof rootRoute
    }
    '/time-tracking': {
      id: '/time-tracking'
      path: '/time-tracking'
      fullPath: '/time-tracking'
      preLoaderRoute: typeof TimeTrackingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance-management': typeof AttendanceManagementRoute
  '/dashboard': typeof DashboardRoute
  '/document-management': typeof DocumentManagementRoute
  '/employee-management': typeof EmployeeManagementRoute
  '/payroll-management': typeof PayrollManagementRoute
  '/recruitment': typeof RecruitmentRoute
  '/time-tracking': typeof TimeTrackingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance-management': typeof AttendanceManagementRoute
  '/dashboard': typeof DashboardRoute
  '/document-management': typeof DocumentManagementRoute
  '/employee-management': typeof EmployeeManagementRoute
  '/payroll-management': typeof PayrollManagementRoute
  '/recruitment': typeof RecruitmentRoute
  '/time-tracking': typeof TimeTrackingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/attendance-management': typeof AttendanceManagementRoute
  '/dashboard': typeof DashboardRoute
  '/document-management': typeof DocumentManagementRoute
  '/employee-management': typeof EmployeeManagementRoute
  '/payroll-management': typeof PayrollManagementRoute
  '/recruitment': typeof RecruitmentRoute
  '/time-tracking': typeof TimeTrackingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance-management'
    | '/dashboard'
    | '/document-management'
    | '/employee-management'
    | '/payroll-management'
    | '/recruitment'
    | '/time-tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance-management'
    | '/dashboard'
    | '/document-management'
    | '/employee-management'
    | '/payroll-management'
    | '/recruitment'
    | '/time-tracking'
  id:
    | '__root__'
    | '/'
    | '/attendance-management'
    | '/dashboard'
    | '/document-management'
    | '/employee-management'
    | '/payroll-management'
    | '/recruitment'
    | '/time-tracking'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceManagementRoute: typeof AttendanceManagementRoute
  DashboardRoute: typeof DashboardRoute
  DocumentManagementRoute: typeof DocumentManagementRoute
  EmployeeManagementRoute: typeof EmployeeManagementRoute
  PayrollManagementRoute: typeof PayrollManagementRoute
  RecruitmentRoute: typeof RecruitmentRoute
  TimeTrackingRoute: typeof TimeTrackingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceManagementRoute: AttendanceManagementRoute,
  DashboardRoute: DashboardRoute,
  DocumentManagementRoute: DocumentManagementRoute,
  EmployeeManagementRoute: EmployeeManagementRoute,
  PayrollManagementRoute: PayrollManagementRoute,
  RecruitmentRoute: RecruitmentRoute,
  TimeTrackingRoute: TimeTrackingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/attendance-management",
        "/dashboard",
        "/document-management",
        "/employee-management",
        "/payroll-management",
        "/recruitment",
        "/time-tracking"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/attendance-management": {
      "filePath": "attendance-management.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/document-management": {
      "filePath": "document-management.tsx"
    },
    "/employee-management": {
      "filePath": "employee-management.tsx"
    },
    "/payroll-management": {
      "filePath": "payroll-management.tsx"
    },
    "/recruitment": {
      "filePath": "recruitment.tsx"
    },
    "/time-tracking": {
      "filePath": "time-tracking.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
