/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as PublicAuthImport } from './routes/_public/auth'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/_dashboard'
import { Route as PublicAuthLoginImport } from './routes/_public/auth/login'
import { Route as AuthenticatedDashboardResumeImport } from './routes/_authenticated/_dashboard/resume'
import { Route as AuthenticatedDashboardFindJobsImport } from './routes/_authenticated/_dashboard/find-jobs'
import { Route as AuthenticatedDashboardDashboardImport } from './routes/_authenticated/_dashboard/dashboard'
import { Route as AuthenticatedDashboardApplicationsImport } from './routes/_authenticated/_dashboard/applications'
import { Route as PublicAuthGoogleCallbackImport } from './routes/_public/auth/google/callback'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PublicAuthRoute = PublicAuthImport.update({
  path: '/auth',
  getParentRoute: () => PublicRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const PublicAuthLoginRoute = PublicAuthLoginImport.update({
  path: '/login',
  getParentRoute: () => PublicAuthRoute,
} as any)

const AuthenticatedDashboardResumeRoute =
  AuthenticatedDashboardResumeImport.update({
    path: '/resume',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

const AuthenticatedDashboardFindJobsRoute =
  AuthenticatedDashboardFindJobsImport.update({
    path: '/find-jobs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

const AuthenticatedDashboardDashboardRoute =
  AuthenticatedDashboardDashboardImport.update({
    path: '/dashboard',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

const AuthenticatedDashboardApplicationsRoute =
  AuthenticatedDashboardApplicationsImport.update({
    path: '/applications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

const PublicAuthGoogleCallbackRoute = PublicAuthGoogleCallbackImport.update({
  path: '/google/callback',
  getParentRoute: () => PublicAuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthImport
      parentRoute: typeof PublicImport
    }
    '/_authenticated/_dashboard/applications': {
      id: '/_authenticated/_dashboard/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedDashboardApplicationsImport
      parentRoute: typeof AuthenticatedDashboardImport
    }
    '/_authenticated/_dashboard/dashboard': {
      id: '/_authenticated/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardImport
      parentRoute: typeof AuthenticatedDashboardImport
    }
    '/_authenticated/_dashboard/find-jobs': {
      id: '/_authenticated/_dashboard/find-jobs'
      path: '/find-jobs'
      fullPath: '/find-jobs'
      preLoaderRoute: typeof AuthenticatedDashboardFindJobsImport
      parentRoute: typeof AuthenticatedDashboardImport
    }
    '/_authenticated/_dashboard/resume': {
      id: '/_authenticated/_dashboard/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedDashboardResumeImport
      parentRoute: typeof AuthenticatedDashboardImport
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginImport
      parentRoute: typeof PublicAuthImport
    }
    '/_public/auth/google/callback': {
      id: '/_public/auth/google/callback'
      path: '/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof PublicAuthGoogleCallbackImport
      parentRoute: typeof PublicAuthImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardApplicationsRoute: typeof AuthenticatedDashboardApplicationsRoute
  AuthenticatedDashboardDashboardRoute: typeof AuthenticatedDashboardDashboardRoute
  AuthenticatedDashboardFindJobsRoute: typeof AuthenticatedDashboardFindJobsRoute
  AuthenticatedDashboardResumeRoute: typeof AuthenticatedDashboardResumeRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardApplicationsRoute:
      AuthenticatedDashboardApplicationsRoute,
    AuthenticatedDashboardDashboardRoute: AuthenticatedDashboardDashboardRoute,
    AuthenticatedDashboardFindJobsRoute: AuthenticatedDashboardFindJobsRoute,
    AuthenticatedDashboardResumeRoute: AuthenticatedDashboardResumeRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicAuthRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthGoogleCallbackRoute: typeof PublicAuthGoogleCallbackRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthGoogleCallbackRoute: PublicAuthGoogleCallbackRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthRoute: PublicAuthRouteWithChildren,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedDashboardRouteWithChildren
  '/auth': typeof PublicAuthRouteWithChildren
  '/applications': typeof AuthenticatedDashboardApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardDashboardRoute
  '/find-jobs': typeof AuthenticatedDashboardFindJobsRoute
  '/resume': typeof AuthenticatedDashboardResumeRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedDashboardRouteWithChildren
  '/auth': typeof PublicAuthRouteWithChildren
  '/applications': typeof AuthenticatedDashboardApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardDashboardRoute
  '/find-jobs': typeof AuthenticatedDashboardFindJobsRoute
  '/resume': typeof AuthenticatedDashboardResumeRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_public/auth': typeof PublicAuthRouteWithChildren
  '/_authenticated/_dashboard/applications': typeof AuthenticatedDashboardApplicationsRoute
  '/_authenticated/_dashboard/dashboard': typeof AuthenticatedDashboardDashboardRoute
  '/_authenticated/_dashboard/find-jobs': typeof AuthenticatedDashboardFindJobsRoute
  '/_authenticated/_dashboard/resume': typeof AuthenticatedDashboardResumeRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/find-jobs'
    | '/resume'
    | '/auth/login'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/find-jobs'
    | '/resume'
    | '/auth/login'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/_dashboard'
    | '/_public/auth'
    | '/_authenticated/_dashboard/applications'
    | '/_authenticated/_dashboard/dashboard'
    | '/_authenticated/_dashboard/find-jobs'
    | '/_authenticated/_dashboard/resume'
    | '/_public/auth/login'
    | '/_public/auth/google/callback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/_public"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_dashboard"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/auth"
      ]
    },
    "/_authenticated/_dashboard": {
      "filePath": "_authenticated/_dashboard.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_dashboard/applications",
        "/_authenticated/_dashboard/dashboard",
        "/_authenticated/_dashboard/find-jobs",
        "/_authenticated/_dashboard/resume"
      ]
    },
    "/_public/auth": {
      "filePath": "_public/auth.tsx",
      "parent": "/_public",
      "children": [
        "/_public/auth/login",
        "/_public/auth/google/callback"
      ]
    },
    "/_authenticated/_dashboard/applications": {
      "filePath": "_authenticated/_dashboard/applications.tsx",
      "parent": "/_authenticated/_dashboard"
    },
    "/_authenticated/_dashboard/dashboard": {
      "filePath": "_authenticated/_dashboard/dashboard.tsx",
      "parent": "/_authenticated/_dashboard"
    },
    "/_authenticated/_dashboard/find-jobs": {
      "filePath": "_authenticated/_dashboard/find-jobs.tsx",
      "parent": "/_authenticated/_dashboard"
    },
    "/_authenticated/_dashboard/resume": {
      "filePath": "_authenticated/_dashboard/resume.tsx",
      "parent": "/_authenticated/_dashboard"
    },
    "/_public/auth/login": {
      "filePath": "_public/auth/login.tsx",
      "parent": "/_public/auth"
    },
    "/_public/auth/google/callback": {
      "filePath": "_public/auth/google/callback.tsx",
      "parent": "/_public/auth"
    }
  }
}
ROUTE_MANIFEST_END */
